[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.8.1"

[[constraint]]
  name = "github.com/emicklei/go-restful-openapi"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.18.0"

[[constraint]]
  name = "github.com/google/uuid"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
